#!/usr/bin/env bash
# Runs ON THE JETSON. Starts mediamtx purely as a SINK for the demo's tiled output, so the
# rendered view can be watched from another machine instead of the attached DP-1 monitor.
#
#   ./scripts/serve_rtsp.sh start | stop | status
#
# It deliberately does NOT restream camera sources. In production the cameras are separate
# network devices and the Jetson only pulls and decodes; generating 20 source streams on the
# same box would burn CPU alongside the inference and misrepresent the load. Camera sources
# come from a separate machine — see scripts/serve_rtsp_sources.sh.
#
# The one stream published here is the pipeline's own output: a single NVENC session on
# dedicated encoder silicon, which does not compete with NVDEC or the GPU.
set -uo pipefail
cd "$(dirname "$0")/.."
source scripts/env.sh

MEDIAMTX=build/bin/mediamtx
CONF=build/mediamtx.yml
PID=build/mediamtx.pid
PORT=8554

start() {
  [ -x "$MEDIAMTX" ] || { echo "ERROR: $MEDIAMTX missing — run scripts/setup.sh"; exit 1; }
  stop >/dev/null 2>&1

  # Browsers cannot play RTSP. mediamtx re-publishes the same stream as WebRTC and HLS, which is
  # what makes the tiled output viewable in the dashboard:
  #
  #   WebRTC (:8889) — sub-second latency, the right choice for a live monitoring wall.
  #   HLS    (:8888) — ~5-10s latency, but plays natively in iOS Safari where WebRTC autoplay is
  #                    awkward. Kept as the mobile/compatibility fallback.
  #
  # webrtcAdditionalHosts carries the LAN address into the ICE candidates; without it a viewer on
  # another machine negotiates against the Jetson's loopback and the video never starts.
  # Every IPv4 address, not just the first: which one comes first depends on what is up, and the
  # USB-C link (192.168.55.1) has to work with WiFi off, when there is no LAN address at all.
  LANIP=$(hostname -I 2>/dev/null | tr ' ' '\n' | grep -E '^[0-9]+(\.[0-9]+){3}$' | paste -sd, -)
  cat > "$CONF" <<EOF
# Generated by scripts/serve_rtsp.sh — do not edit by hand.
logLevel: warn
rtspAddress: :${PORT}

# The control API is what lets the dashboard distinguish "server down" from "server up but nobody
# is publishing" — two states that look identical from the viewer's side (both are a black box)
# but have completely different fixes. Without it the only honest thing the UI could say is
# "no video", which tells an operator nothing.
api: yes
# Loopback: only services/api.py reads it, from this same host. The RTSP/WebRTC/HLS listeners
# below stay on all interfaces because a remote browser is the entire point of them.
apiAddress: 127.0.0.1:9997

webrtc: yes
webrtcAddress: :8889
webrtcLocalUDPAddress: :8189
webrtcAdditionalHosts: [${LANIP}]

hls: yes
hlsAddress: :8888
hlsVariant: lowLatency
hlsAlwaysRemux: yes

paths:
  # The pipeline publishes here via rtspclientsink; viewers read the same path.
  safety:
EOF

  nohup "$MEDIAMTX" "$CONF" > build/mediamtx.log 2>&1 &
  echo $! > "$PID"
  sleep 2
  kill -0 "$(cat "$PID")" 2>/dev/null || {
    echo "ERROR: mediamtx failed to start:"; tail -5 build/mediamtx.log; exit 1; }

  echo "==> mediamtx on :${PORT}  (WebRTC :8889 · HLS :8888)"
  echo "    demo output: rtsp://$(hostname):${PORT}/safety"
}

stop() {
  [ -f "$PID" ] && { kill "$(cat "$PID")" 2>/dev/null; rm -f "$PID"; }
  pkill -f "$MEDIAMTX" 2>/dev/null
  echo "==> stopped"
}

status() {
  local n; n=$(pgrep -fc "$MEDIAMTX" 2>/dev/null || echo 0)
  echo "  mediamtx: $([ "$n" -gt 0 ] && echo running || echo stopped)"
  [ "$n" -gt 0 ] && curl -s -m 3 http://127.0.0.1:9997/v3/paths/list | python3 -c '
import json, sys
try:
    items = json.load(sys.stdin).get("items", [])
except Exception:
    sys.exit(0)
for p in items:
    src = (p.get("source") or {}).get("type") or "none"
    print("  path %s: ready=%s source=%s readers=%d"
          % (p["name"], p["ready"], src, len(p.get("readers", []))))
' 2>/dev/null
  return 0
}

case "${1:-start}" in
  start)  start ;;
  stop)   stop ;;
  status) status ;;
  *) echo "usage: $0 {start|stop|status}"; exit 1 ;;
esac
